name: elm327_workspace
publish_to: none

environment:
  sdk: ^3.8.0

workspace:
  - packages/ble_core
  - packages/elm327_obd
  - packages/elm327_obd_vehicle_pids
  - packages/elm327_obd_bluetooth
  - apps/elm327_demo

dev_dependencies:
  melos: ^6.3.3
